project_name: control_v2
load_model_name: planes_channel180_minchan_31-FNO-reproduce.pth
comments: 5-no apply bc
display_variables:
  - comments
  - policy_name
  - reward_type
  - noise_scale
  - timestep
DATA_FOLDER: ./data/planes_channel180_minchan
path_name: planes_channel180_minchan
model_name: FNO2dObserver
use_v_plane: false
modes: 12
width: 32
vis_sample_img: false
timestep: 1000
noise_scale: 0.0
use_spectral_conv: false
downsample_rate: 1
x_range: 32
y_range: 32
# policy_name: fno
# policy_name: rand
policy_name: gt
rand_scale: 1   # this is for rand policy
reward_type: mse

# visualization setttings
vis_frame: 60
vis_interval: 1000  # default, will be overwritten.
output_dir: ./outputs
close_wandb: false