# minchan dataset
DATA_FOLDER: './data/planes_channel180_minchan'
ntrain: 8000
ntest: 2000
project_name: 'fno_vs_unet'
exp_name: '28-RNO-reproduce'
path_name: planes_channel180_minchan
model_name: RNO2dObserverOld
learning_rate: 0.001
weight_decay: 0.0001
step_size: 100
gamma: 0.5
modes: 12
width: 32  # 32 by default
downsample_rate: 1
x_range: 32
y_range: 32
use_v_plane: false
use_patch: false
timestep: 2
recurrent_model: true
recurrent_index: 0
random_split: false

# small model
width: 34  # 32 by default
batch_size: 32
layer_num: 3
close_wandb: true
epochs: 200

# # large model
# batch_size: 32  # 20
# width: 64
# layer_num: 10
# close_wandb: false
# epochs: 200
