data:
  test_paths: ['data/pino/NS_fine_Re500_T128_part0.npy']
  train_paths: ['data/pino/multi_reynolds_NS_fine_T128.npz']
  # datapath: 'data/NS_fine_Re400_T128_part0.npy'
  # Re: 400
  # total_num: 100
  # offset: 199
  # n_sample: 1
  offset: 80
  testoffset: 80
  n_data_samples: 1
  n_test_samples: 1
  time_interval: 1.0
  nx: 128
  nt: 128
  sub: 1
  sub_t: 2
  shuffle: True
  t_duration: 0.5
  raw_res: [128, 128, 129]
  data_res: [128, 128, 129]  # resolution in 1 second
  pde_res: [128, 128, 129]   # resolution in 1 second

model:
  layers: [64, 64, 64, 64, 64]
  modes1: [8, 8, 8, 8]
  modes2: [8, 8, 8, 8]
  modes3: [8, 8, 8, 8]
  fc_dim: 128
  act: gelu
  num_pad: 4
  pad_ratio: 0.0625

train:
  start_iter: 0
  batchsize: 4
  epochs: 10000
  num_iter: 20_001
  milestones: [500, 1500, 3000, 4000, 6000]
  base_lr: 0.0025
  scheduler_gamma: 0.5
  ic_loss: 5.0
  f_loss: 1.0
  xy_loss: 0.0
  save_step: 5000
  eval_step: 5000
  save_dir: 'Re400-FDM'
  save_name: 'PINO-finetune-Re400-1s.pt'
  ckpt: 'exp/Re400-1_8s-dat80-PINO/ckpts/model-20000.pt'

test:
  batchsize: 4  # 4
  data_res: [128, 128, 65]

log:
  project: PINO-NS
  group: Re400-finetune-1_8s-dat80-PINO
  logdir: Re400-1_8s-dat80-PINO
  entity: zlzhao-pino